### PR TITLE
I have re-coded telegram bot using aioram and added some structure

### PR DESCRIPTION
**Pull request by krystlepalace**
There's  may be some troubles with requirements.txt, but everything work well for me.

### CODE REVIEW

**Comment by krystlepalace** [comment]
Please make sure you feel ok about my improvements

**Comment by amirzenoozi** [comment]
Dear @krystlepalace 

Thanks for your contribution. during checking your pull request I realized you moved several files, but I do not get why they should moved to another folder. So please let me know about this change. In the end, I think changing the telegram bot structure can be a good change. and I will be grateful. 

Please let me know When you think the pull request is ready.

**Comment by krystlepalace** [comment]
I've moved the bot-related files to a separate folder to make its architecture clearer and simpler. If you mean why I copied the file 'utils.py' to a separate folder - for the same reason. These changes do not affect the operation of other scripts in any way, so you dont need to worry about.
I think pull request is ready now.

**Comment by amirzenoozi** [comment]
I think the telegram bot does not need a specific folder. and all their shared scripts and codes should be in a single file/folder. So I think it is simpler and better if you don't copy the files in the `bot` folder and only add or change the existing files or folder. If other users clone this code I think it will be a little confusing if we have the same files inside the `bot` folder however the other scripts work fine.

**Comment by krystlepalace** [comment]
I made changes you was asking for.
Now no more bot/ folder, script bot.py and config.py is in main folder of project, and handlers/ folder too.
I think all work is done now.

**Comment by amirzenoozi** [comment]
Thank you so much, but I think you forgot the `__pycache__` folder. Please remove this folder too.

**Comment by krystlepalace** [comment]
I am so sorry about this. Removed.

**Pull request merged**
